// pipeline {
//     agent any
//     options {
//         skipStagesAfterUnstable()
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 sh 'mvn -B -DskipTests clean package'
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh 'mvn test'
//             }
//             post {
//                 always {
//                     junit 'target/surefire-reports/*.xml'
//                 }
//             }
//         }
//         stage('Deliver') { 
//             steps {
//                 sh './jenkins/scripts/deliver.sh' 
//             }
//         }
//     }
// }



pipeline {
    agent none  // Required top-level agent when using per-stage agents

    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            agent { label 'slave1' }
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            agent { label 'slave1' }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            agent { label 'slave2' }  // Docker runs on slave2
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
